### ISSUE TITLE
how to set model parameters

### ISSUE THREAD

**Issue by zsy0828** [google-deepmind/graphcast#102]
HI, I read the code ,and I see zhe mlp's hidden is 32, and mesh2mesh graph's messagepassing is 4 times, but i find those parameters in graphcast paper is 512 and 16, i write the model by dgl and pytorch in https://github.com/zsy0828/graphcast, but  if i set mlp's hiddim=512, and num_gnn_layer=16, it will OOM  on CUDA.
So, what the real parameter's of this model, could you tell me.

**Comment by alvarosg** [comment]
We provided a few sets of models explained [here](https://github.com/google-deepmind/graphcast/blob/main/README.md). The main model indeed uses latent hiddim=512, and num_gnn_layer=16. If that runs out of memory you may need a larger GPU, or a more efficient implementation.
