### ISSUE TITLE
Accessing ECMWF Data

### ISSUE THREAD

**Issue by hammad93** [google-deepmind/graphcast#26]
For some reason, right when your team started collaborating with the ECMWF, they changed their licensing structure on July 1st, 2023 . This meant that my order placed in April was canceled with no notification. How can we access the data and go about doing research? Please reference this issue,
https://github.com/ecmwf/ecmwf-opendata/issues/30

**Comment by mjwillson** [comment]
Closing as this is a question for ECMWF and not related to our project.
