### ISSUE TITLE
JAX error while training

### ISSUE THREAD

**Issue by illuSION-crypto** [google-deepmind/graphcast#30]
Hello, I wonder if anyone encountered the same question. When I try the graphcast_demo.ipynb, every  step is okay until training, and I see this:
![image](https://github.com/google-deepmind/graphcast/assets/56497487/918b23f5-b3cd-4634-8f2c-9c3b940d5852)
![image](https://github.com/google-deepmind/graphcast/assets/56497487/4ffd3b96-3c12-472b-b7f9-32f3347693f9)
I use the example data given in the google cloud bucket，and change nothing about code, anyone know how to solve it? My jax version is 0.4.20 with cuda 11.8

**Comment by AndrewYangnb** [comment]
I meet the same Error, I also want to know the reason and how to fix it.

**Comment by chrisagblake** [comment]
Me too. I'm on jax 0.4.20 and cuda 12.3 using an nvidia GPU (4090).

**Comment by chrisagblake** [comment]
I managed to fix this issue by installing an older version of xarray. I had version 2023.12.0 installed and when I downgraded to 2023.7.0 to replicate the colab example it worked.
```bash
pip uninstall xarray
pip install xarray==2023.7.0
```

**Comment by illuSION-crypto** [comment]
> I managed to fix this issue by installing an older version of xarray. I had version 2023.12.0 installed and when I downgraded to 2023.7.0 to replicate the colab example it worked.
> 
> ```shell
> pip uninstall xarray
> pip install xarray==2023.7.0
> ```

That's great, I also solved this issue by this way, thank you!

**Comment by mjwillson** [comment]
After this commit: https://github.com/google-deepmind/graphcast/commit/8debd7289bb2c498485f79dbd98d8b4933bfc6a7 we should be compatible with more recent versions of xarray too. Closing but please re-open if you still see the issue running from HEAD.
