### ISSUE TITLE
How to save the model

### ISSUE THREAD

**Issue by AndrewYangnb** [google-deepmind/graphcast#34]
I have successfully run `graphcast_demo.ipynb` locally, but how do I **save the model parameters** after the final training using the sample dataset?

I try using code:
```
# @title Autoregressive rollout (keep the loop in JAX)
print("Inputs:  ", train_inputs.dims.mapping)
print("Targets: ", train_targets.dims.mapping)
print("Forcings:", train_forcings.dims.mapping)

predictions = run_forward_jitted(
    rng=jax.random.PRNGKey(0),
    inputs=train_inputs,
    targets_template=train_targets * np.nan,
    forcings=train_forcings)
predictions

with open(f"dm_graphcast/params/test.npz", "wb") as f:
    checkpoint.dump(f, graphcast.CheckPoint)
```

But it doesn't work.

**Comment by idharssi2020** [comment]
What about trying this 

`ck_file='Gcloud/params/GraphCast_small - ERA5 1979-2015 - resolution 1.0 - pressure levels 13 - mesh 2to5 - precipitation input and output.npz'`
`print("Reading Checkpoint=", ck_file)`
`ckpt = checkpoint.load(ck_file, graphcast.CheckPoint)`
`print("Model description:\n", ckpt.description, "\n")`
`params = ckpt.params`
`model_config = ckpt.model_config`
`task_config = ckpt.task_config`


_Perform optimisation_


`ck_file2=f"GC_new.npz"`      
`print("Saving Checkpoint=", ck_file2)`
`with open(ck_file2, "wb") as f:`
`        checkpoint.dump(f, ckpt)`

**Comment by tewalds** [comment]
You need to pass a `graphcast.CheckPoint` object, not the class definition. In the colab that is the `ckpt` variable, but if you're not changing it, you can also just download the file directly. If you want to change it (eg fine tune it), you'll need to construct a new object to pass to `checkpoint.dump`.

**Comment by AndrewYangnb** [comment]
> You need to pass a `graphcast.CheckPoint` object, not the class definition. In the colab that is the `ckpt` variable, but if you're not changing it, you can also just download the file directly. If you want to change it (eg fine tune it), you'll need to construct a new object to pass to `checkpoint.dump`.

ok, thank you, i have got it.

**Comment by AndrewYangnb** [comment]
> You need to pass a `graphcast.CheckPoint` object, not the class definition. In the colab that is the `ckpt` variable, but if you're not changing it, you can also just download the file directly. If you want to change it (eg fine tune it), you'll need to construct a new object to pass to `checkpoint.dump`.
