### ISSUE TITLE
Create a grib file of the predictions

### ISSUE THREAD

**Issue by sailgrib** [google-deepmind/graphcast#39]
Hi everybody,

I am trying to create a grib file with a subset (10 meter wind and pressure at sea level) of the predictions but do not succeed.
Can you help me creating a grib file?

Thanks,

Henri

**Comment by jblestang** [comment]
Glad to see someone wondering about GRIB generation from GraphCast! Are you able to generate the prediction? If yes then generating the Hrin shall be relatively straight forward. What is the blocking point?

**Comment by jblestang** [comment]
`xarray.Dataset` can be converted to netcdf format and netcdf can be converted to grib using cdo (install using `apt install cdo`)

**Comment by sailgrib** [comment]
Thanks, I was missing the intermediate conversion to netcdf.

**Comment by jblestang** [comment]
You can run `cdo -f grb copy input.nc output.grb` to convert.

**Comment by mjwillson** [comment]
Closing as sounds like this is solved. GRIB output isn't something we directly support in this codebase but you can do it yourself as noted above.
