### ISSUE TITLE
Model Predict

### ISSUE THREAD

**Issue by Vitalitypi** [google-deepmind/graphcast#4]
Hello, can this model predict the weather in N20~N40, E110-E130？I see that the model can only train data with latitudes starting from -90 and ending in 90. How can I train data with latitudes between 20 and 40? When training data from latitude 20 to 40, errors are reported in calculating losses!

**Comment by alvarosg** [comment]
The model as it is set up assumes the whole globe, and uses a mesh around the whole globe. We have not really tried using it in smaller patches of data only. That said, it should probably be possible, my guess is that you would need to build a smaller mesh for the region you are interested on, rather than using the full refined icosahedral mesh which covers the whole globe.

**Comment by Vitalitypi** [comment]
Thank you very much

**Comment by Vitalitypi** [comment]
> The model as it is set up assumes the whole globe, and uses a mesh around the whole globe. We have not really tried using it in smaller patches of data only. That said, it should probably be possible, my guess is that you would need to build a smaller mesh for the region you are interested on, rather than using the full refined icosahedral mesh which covers the whole globe.



> The model as it is set up assumes the whole globe, and uses a mesh around the whole globe. We have not really tried using it in smaller patches of data only. That said, it should probably be possible, my guess is that you would need to build a smaller mesh for the region you are interested on, rather than using the full refined icosahedral mesh which covers the whole globe.

Thank you very much!

**Comment by Vitalitypi** [comment]
> The model as it is set up assumes the whole globe, and uses a mesh around the whole globe. We have not really tried using it in smaller patches of data only. That said, it should probably be possible, my guess is that you would need to build a smaller mesh for the region you are interested on, rather than using the full refined icosahedral mesh which covers the whole globe.

Thank you very much!

**Comment by Vitalitypi** [comment]
no, thanks!



---Original---
From: ***@***.***&gt;
Date: Wed, May 8, 2024 20:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [google-deepmind/graphcast] Model Predict (Issue #4)




 
Did you figure out how to use the model for a specific region?
