### ISSUE TITLE
Predicting Forecast for 10 Days , 5 Days

### ISSUE THREAD

**Issue by Ahsankhan71** [google-deepmind/graphcast#50]
Hi,
I am very new to GraphCast. I wanted to know how can I have the forecast of 10 days and 5 days. I did run the notebook successfully (graphcast_demo.ipynb), but I did not catch up with the changes required for forecasting upto different (user-defined) timesteps.
Right now, I am confused about how can i use any pre-trained model of GraphCast and predict 10days, 5 days forecast?
I would really appreciate if someone explains the necessary steps for it clearly so I can understand them easily. 
Thank you very much!

**Comment by tvonich** [comment]
To start, you can download the example data from https://console.cloud.google.com/storage/browser/dm_graphcast;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

After that, you'll be able to select the desired time steps when you run the notebook as long as you have the example data with 40 time steps (10 days).

**Comment by Ahsankhan71** [comment]
Thank you very much!
In the notebook Graphcast_demo, I saw the option to choose the timestamps of 40. 
I really do appreciate your help. 
:)
