### ISSUE TITLE
Obtaining successive forecasts based on previous predictions

### ISSUE THREAD

**Issue by iop-c** [google-deepmind/graphcast#51]
Hi all,

I am wondering how to use the predictions from GraphCast as inputs to produce forecasts for the next time steps. I’m also a beginner in GraphCast and some of the tools and data this code uses.

I’ve run the graphcast_demo.ipynb code with data from ERA5 (using the function download_era5_data from https://github.com/google-deepmind/graphcast/issues/22) and downloaded data from one day (let’s say 2022-12-31, with time values ['2022-12-31T00:00:00.000000000', '2022-12-31T06:00:00.000000000',  '2022-12-31T12:00:00.000000000', '2022-12-31T18:00:00.000000000'] ) to use that one as  'example_batch' instead of the example data.  In that way I can obtain some predictions. Now I’d want to use those predictions to produce successive forecasts for the next days (up to 2023-1-10, so I can obtain the next 10 days forecast).

The 'predictions' xarray.Dataset is somewhat different from the input data. The 'time' coordinate is now a timedelta variable and the datetime coordinate is missing in the predictions xarray. Also, the following variables are missing 'toa_incident_solar_radiation', 'geopotential_at_surface' and 'land_sea_mask'. What should be the process to complete and reformat the 'predictions' so it can be used again as input to produce the next forecast values? Or maybe what I’m trying to do should be done in other way?

Thanks in advance!

**Comment by ElNino9495** [comment]
@iop-c where you able to do this?
