### ISSUE TITLE
How to get the data in the paper?

### ISSUE THREAD

**Issue by wtestererer** [google-deepmind/graphcast#58]

**Comment by alvarosg** [comment]
Thanks for your messsage. 

Full model training requires downloading the [ERA5](https://www.ecmwf.int/en/forecasts/datasets/reanalysis-datasets/era5) dataset, available from [ECMWF](https://www.ecmwf.int/). This can best be accessed as Zarr from [Weatherbench2's ERA5 data](https://weatherbench2.readthedocs.io/en/latest/data-guide.html#era5) (see the 6h downsampled versions).
