### ISSUE TITLE
weights license - use of graphcast

### ISSUE THREAD

**Issue by StevenEarle-NCO** [google-deepmind/graphcast#59]
I've read through the license (https://creativecommons.org/licenses/by-nc-sa/4.0/) and all of the terms are clear except the NonCommercial use. As an employee with the US Government (National Weather Service), we're not going to directly use graphcast weights for commercial purposes. However, the output data and images we create are planned to be on public servers. Once they are Government public servers, then they can be used by corporations to make a profit (or... commercial purposes). Is this OK, since we're not directly using the model weights for commercial purposes?

**Comment by alvarosg** [comment]
Thank you for your email. My first intuition is that derivatives of the weights with non commercial licence (output model data) by default may have to be subject to the same non commercial licence, but let me double check with our legal team and get back to you.

**Comment by StevenEarle-NCO** [comment]
Hi @alvarosg; thanks for looking into this for me. Do you have any update from your legal team? I have noticed some of my counterparts in other national/Government run weather agencies have published images/data publicly using the google deepmind model (including weights). For example, one of them does it but makes clear the license:
"Graphical products from these experimental models are provided under a [CC-BY-NC-SA-4 licence]"
I can certainly ping you privately to discuss the other groups doing this if you'd like.

Wondering if we'd be OK doing the same. Really appreciate your support!

**Comment by bmkor** [comment]
Mind I chipping in here? First, many thanks for open sourcing this wonderful project. 

As working in the Hong Kong official meteorological centre, we appreciate this work very much and would like to use graphcast for generating some forecast products; especially related with Tropical cyclone. 

We got a similar question here, despite non-commercial use, we are pondering the question on releasing any forecast products based on graphcast to the public. Not sure if there is any more discussion or even suggestions so far? Grateful if any light could be thrown here. Thank you very much.

**Comment by alvarosg** [comment]
Hi both, thank you again for your questions. 

Please can you drop a brief email with your request to [graphcast@google.com](mailto:graphcast@google.com) and our partnerships manager will get back to you.

**Comment by bmkor** [comment]
We just sent the email. Thank you very much @alvarosg
