### ISSUE TITLE
Dataset for 10 day forecast

### ISSUE THREAD

**Issue by siliconskies** [google-deepmind/graphcast#6]
Hi there,
I'm trying to run GraphCast for the 10 day forecast like it was done in the paper. Unless I'm mistaken the example data that was provided in the Google Cloud Bucket only datasets for up to 3 days. Where can I find the dataset that was used for the 10 day run?

**Comment by alvarosg** [comment]
Hi, thanks for your reply. 

Those inputs are only provided as dataset samples to replicate training in the paper which only goes to 3 days.

For producing 10 day forecasts, I would recommend to obtain data directly from ERA5, which you may be able to obtain via [WeatherBench2](https://weatherbench2.readthedocs.io/en/latest/data-guide.html).

Hope this helps!
