### ISSUE TITLE
 when is the prediction result of this demo?

### ISSUE THREAD

**Issue by ws1234321** [google-deepmind/graphcast#62]
Hello, when is the prediction result of this demo? I entered three times and it seems that the result is the value of the middle time. Does any teacher know the reason? Please feel free to comment, thank you.

**Comment by tewalds** [comment]
You may find #32 and #56 helpful.

**Comment by ws1234321** [comment]
Thank you. I think I understand a little. I will make changes in an aligned way. Thank you very much for your advice.
