### ISSUE TITLE
Fine-Tuning Strategy for the GraphCast Operational Model

### ISSUE THREAD

**Issue by MinchanJeong** [google-deepmind/graphcast#66]
Greetings,

Firstly, I'd like to express my admiration for your impressive work.

I have a question regarding the fine-tuning process for the GraphCast in the operational model, specifically how it was adapted without requiring Total Precipitation as an input.

From my understanding of the model architecture, once the MLP embedder encodes the grid node features, the input dataset are not directly fed into the model. This leads me to speculate that only the MLP embedder for grid node features might be trained, with the other modules being frozen.

Could you confirm if my reasoning is accurate or if there are any crucial aspects I've overlooked? Clarification on this would greatly aid my research.

Thank you very much in advance!

**Comment by alvarosg** [comment]
Thanks for your email.

Just to clarify, the operational model was trained separately from the non-operational model. The non-operational data was trained on ERA5 on 37 pressure levels, and using precipitation as inputs.

The operational one was separately trained from scratch on ERA5 only on 13 pressure levels, and without taking precipitation as input. And then fine-tuned on the operational data.

Hope this helps!

**Comment by MinchanJeong** [comment]
Thank you very much for the explanation! My inquiry is resolved.
