### ISSUE TITLE
How was the Graphcast Small 1.0 degree Reanalysis made?

### ISSUE THREAD

**Issue by tvonich** [google-deepmind/graphcast#72]
Hello,
Was it simply e quarter degree reanalysis values pulled from whole number lat/lon positions or were the values actually averaged over the 1.0 degree region?

**Comment by alvarosg** [comment]
Thanks for your message.

It was done by bilinear interpolation, which for this grid is indeed equivalent to pulling the values at the whole lat/lon positions. 

It was done this way so the 1 deg values would match the statistics of the 0.25 deg values, and the metrics could be compared across resolutions.

Hope this helps!

**Comment by tvonich** [comment]
> Thanks for your message.
> 
> It was done by bilinear interpolation, which for this grid is indeed equivalent to pulling the values at the whole lat/lon positions.
> 
> It was done this way so the 1 deg values would match the statistics of the 0.25 deg values, and the metrics could be compared across resolutions.
> 
> Hope this helps!

That helps tremendously!

 I am finishing up the results for a paper I am submitting to GRL and I'd like to test the methods with a different date. I've tried

**Comment by tvonich** [comment]
This helps tremendously!

I am preparing to submit a paper to GRL using Graphcast Small results and I'd like to reproduce the results with data other than that provided in the cloud storage bucket. When I download my own ERA5 1.0 degree reanalysis from NCAR's RDA for Jan 1, 2022 I get substantially different loss values. Is there any post-processing that is done with the bilinear interpolation method, or are data values purely replicated from the whole number lat/lons from the 0.25 degree reanalysis?
