### ISSUE TITLE
Training duration of pre-training model

### ISSUE THREAD

**Issue by zhongmengyi** [google-deepmind/graphcast#77]
Hello, I would like to ask how long it took to train the three pre-training models provided by Graphcast, and how much memory they occupy? Is there any specific data? Thanks!

**Comment by alvarosg** [comment]
Thanks for your question.

Training the main 0.25 deg ERA5 GraphCast those models took about four weeks on 32 TPU v4 devices (each TPU with 32GB of RAM). About two weeks for the initial 1 step phase, and another two weeks for the 2-12 steps annealing. 

However, for ease of training (see more details [here](https://github.com/google-deepmind/graphcast/issues/55)) I would recommend to use GPUs/TPUs with more memory than 32GB.

The operational one took about the same, except that it has an additional phase of 1AR fine-tuning in between those two phases, which takes an extra day.

The 1 deg model takes about 1.5 days to train in total.
