### ISSUE TITLE
Prediction variables

### ISSUE THREAD

**Issue by ElNino9495** [google-deepmind/graphcast#91]
Can graphcast be used to only predict precipitation or can it also predict temperature, relative humidity, net surface solar radiation?

**Comment by alvarosg** [comment]
Thanks for your message. The details of the variables it predicts are in our [paper](https://www.science.org/doi/10.1126/science.adi2336), also available as a pre-print in arxiv. In principle the model can also be trained to predict other variables, although this is outside the scope of the current work.
