### ISSUE TITLE
Comparison of Graphcast and Copernicus

### ISSUE THREAD

**Issue by ElNino9495** [google-deepmind/graphcast#92]
I want to conduct a study comparing the results of Graphcast with Copernicus from the year 2008-2023.
Is it feasible to conduct such a study?

**Comment by alvarosg** [comment]
For years 2022 and beyond, you could run `GraphCast_operational`, which was trained up to 2021. For years 2018-2021 you could run `GraphCast`, which was trained up to 2017.

However for 2017 However, all of the models we provide train on data up to 2017, so unfortunately it is not possible to evaluate them on those years, as they may be overfitting to the training data, and it would not be a fair evaluation.
